#!/usr/bin/perl

use strict ;
use warnings ;
use v5.18 ;

use lib `fvwm-perllib dir`;
use FVWM::Module;
use Sys::Statistics::Linux ;
use Math::Round qw( round ) ;
#use Data::Dump qw( dump ) ;

my $lxs = Sys::Statistics::Linux->new(
    cpustats  => 1,
    memstats  => 1,
    diskstats => 1,
    netstats  => 1,
    ) ;

$lxs->init ;

my $last_desk = 1 ;
my $desk_min = 1 ;
my $desk_max = 7 ;

my $cpudiv = 2 ;
my $cpusum = my $cpucnt = 0 ;
my @graphdata = (0) x 20 ;
my @mnths = qw( Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec ) ;
my @cmds = () ;

my $module = new FVWM::Module(
    Name => 'FuBarStats',
    Debug => 0,
    );

##  Setup periodic alarm for during playback.
$SIG{ALRM} = \&polling ;
my $pollinterval = 1 ;

##  Detect and update any desktop changes.
my $page_tracker = $module->track("PageInfo") ;
$page_tracker->observe(sub {
	my ($module, $tracker, $info) = @_;
        update_desk($info->{desk_n}) ;
});

alarm($pollinterval) ;
$module->event_loop ;

####  SUBROUTINES

sub polling {
#    say STDERR "[FuBarStats] Update " ;
    update_bar() if not -e '/tmp/stopfubar' ;
    alarm($pollinterval) ;
    return ;
}

sub update_bar  {

#    my $desk = $desks[$curr_desk] ;
#    update_desk() ;

    my $stats = $lxs->get ;

##      my $cpu0 = round($stats->{cpustats}->{cpu0}->{total}) ;
##      $cpu0 = 99 if $cpu0 == 100 ;
##      $cpusum0 += $cpu0 ;
##  
##      my $cpu1 = round($stats->{cpustats}->{cpu1}->{total}) ;
##      $cpu1 = 99 if $cpu1 == 100 ;
##      $cpusum1 += $cpu1 ;
##      $cpucnt++ ;

    ##  The cpu equation for Sys::Statistics::Linux::CpuStats:
    ##      user + system + iowait = 100 - idle = total
    ##  Here we seek cputot without iowait.

    my $cpu_user = $stats->{cpustats}->{cpu}->{user} ;
    my $cpu_system = $stats->{cpustats}->{cpu}->{system} ;
    my $cpu = round($cpu_user + $cpu_system) ;
    $cpu = 99 if $cpu == 100 ;
    $cpusum += $cpu ;
    $cpucnt++ ;

    my $swapused = round($stats->{memstats}->{swapused}/1024) ;
    my $memtotal = $stats->{memstats}->{memtotal} ;
    my $memused = round(
        ($memtotal - $stats->{memstats}->{realfree})/1024
    ) ;

##    say STDERR "swap : $swapused" ;
##    say STDERR " mem : $memused" ;

    my $netrx = round($stats->{netstats}->{eth0}->{rxbyt}/1024) ;
    $netrx = $netrx < 1000                ? 
        sprintf "%4dKB/s", $netrx         :
        sprintf "%4.2fMB/s", $netrx/1024  ;

    my $nettx = round($stats->{netstats}->{eth0}->{txbyt}/1024) ;
    $nettx = $nettx < 1000                ? 
        sprintf "%4dKB/s", $nettx         :
        sprintf "%4.2fMB/s", $nettx/1024  ;

    my ( $sec, $min, $hr, $mday, $mnth, $foo ) = localtime() ;
    my $padsec = sprintf "%02d", ${sec} ;
    my $date = "$mday ".$mnths[$mnth] ;
    my $hrsmins = sprintf "%02d:%02d:", $hr, $min ;

#    addcmd("SendToModule FuBar ChangeButton z1 Title \"${desk}\"") ;
    addcmd("SendToModule FuBar ChangeButton z2 Title ${cpu}%") ;
    #addcmd("SendToModule FuBar ChangeButton z3 Title ${cpu1}%") ;
    addcmd("SendToModule FuBar ChangeButton z4 Title ${memused}Mb") ;
    #   addcmd("SendToModule FuBar ChangeButton z1 Title ${swapused}Mb") ;
    addcmd("SendToModule FuBar ChangeButton z5 Title ${netrx}") ;
    addcmd("SendToModule FuBar ChangeButton z6 Title ${nettx}") ;
    addcmd("SendToModule FuBar ChangeButton z9 Title $padsec") ;

    if ($sec%$cpudiv == 0) {

##          my $cpuavg0 = $cpusum0/$cpucnt ;
##          my $cpuavg1 = $cpusum1/$cpucnt ;
##          pop @graphdata0 ;
##          pop @graphdata1 ;
##          unshift(@graphdata0, int($cpuavg0/16.6667)) ;
##          unshift(@graphdata1, int($cpuavg1/16.6667)) ;

        my $cpuavg = $cpusum/$cpucnt ;
        pop @graphdata ;
        unshift(@graphdata, int($cpuavg/16.6667)) ;

        addcmd("SendToModule FuBar ChangeButton g0 Icon " . 
            join("", @graphdata[0..3]).".xbm" ) ;
        addcmd("SendToModule FuBar ChangeButton g1 Icon " . 
            join("", @graphdata[4..7]).".xbm" ) ;
        addcmd("SendToModule FuBar ChangeButton g2 Icon " . 
            join("", @graphdata[8..11]).".xbm" ) ;
        addcmd("SendToModule FuBar ChangeButton g3 Icon " . 
            join("", @graphdata[12..15]).".xbm" ) ;
        addcmd("SendToModule FuBar ChangeButton g4 Icon " . 
            join("", @graphdata[16..19]).".xbm" ) ;

#        $cpucnt = $cpusum0 = $cpusum1 = 0 ;
        $cpucnt = 0 ;
        $cpusum = 0 ;
    }

    if ($sec%60 == 0) {
        addcmd("SendToModule FuBar ChangeButton z7 Title \"${date}\"") ;
        addcmd("SendToModule FuBar ChangeButton z8 Title ${hrsmins}") ;
    } ;

    sendcmds() ;
}

sub addcmd   { push @cmds, $_[0] } ;

sub sendcmds {
    foreach (@cmds) { $module->send($_) } ;
    @cmds = () ;
}

sub update_desk  {

#my $lastdesk = 1 ;
#my $desk_min = 1 ;
#my $desk_max = 7 ;

##      my $page_hash = $page_tracker->data ;
##      my $curr_desk = $page_hash->{'desk_n'} ;

    my $curr_desk = shift ;
    return 0 if $curr_desk == $last_desk ;
    #say STDERR "Desk: $curr_desk" ;

    for (my $desk = $desk_min ; $desk <= $desk_max ; $desk++ )  {
        if ($desk == $curr_desk)  {
            addcmd("Colorset " . ($desk + 100) . " fg #6993BF, bg Gray20") 
        } else {
            addcmd("Colorset " . ($desk + 100) . " fg gray60, bg gray10")
        }
    }

    $last_desk = $curr_desk ;
    addcmd("UpdateStyles") ;
    sendcmds() ;
}


##sub update_desk  {
##
##    my $desk_min = 1 ;
##    my $desk_max = 7 ;
##    my $page_hash = $page_tracker->data ;
##    my $curr_desk = $page_hash->{'desk_n'} ;
##
##    if ($curr_desk > $desk_min and $curr_desk < $desk_max)  {
##        my $num = 100 + $curr_desk - 1 ;
##        addcmd("Colorset " . $num++ . " fg gray60, bg gray10") ;
##        addcmd("Colorset " . $num++ . " fg LightSlateGray, bg Gray20") ;
##        addcmd("Colorset " . $num++ . " fg gray60, bg gray10") ;
##    } elsif ( $curr_desk == $desk_min )  {
##        addcmd("Colorset " . ($desk_max + 100) . " fg gray60, bg gray10") ;
##        addcmd("Colorset " . ($desk_min + 100) . " fg LightSlateGray, bg Gray20") ;
##        addcmd("Colorset " . ($desk_min + 101) . " fg gray60, bg gray10") ;
##    } elsif ( $curr_desk == $desk_max )  {
##        addcmd("Colorset " . ($desk_min + 100) . " fg gray60, bg gray10") ;
##        addcmd("Colorset " . ($desk_max + 100) . " fg LightSlateGray, bg Gray20") ;
##        addcmd("Colorset " . ($desk_max + 99)  . " fg gray60, bg gray10") ;
##    }
##}



















